return {
  {
    category = "Navigation",
    instruction = "Use / to search for 'subtract' in this file. Press n to cycle matches.",
    hint = "Type /subtract then Enter. Press n for next, N for previous (both center with zz).",
    file = "src/calculator.py",
  },
  {
    category = "Navigation",
    instruction = "Use <C-d> to scroll down half a page. Then <C-u> to scroll back up.",
    hint = "Both keep the cursor centered on screen.",
    file = "src/calculator.py",
  },
  {
    category = "Telescope",
    instruction = "Use <leader>ff to find 'advanced.py' and open it.",
    hint = "Start typing the filename in the Telescope prompt.",
    file = "src/calculator.py",
  },
  {
    category = "Telescope",
    instruction = "Use <leader>fg to grep for 'assert' across the project.",
    hint = "Live grep searches all files. Navigate results with j/k, Enter to jump.",
    file = "src/calculator.py",
  },
  {
    category = "LSP",
    instruction = "Place cursor on 'Calculator' (line 4) and press gd to go to its definition.",
    hint = "gd jumps to where the symbol is defined. On an import, press gd again to follow through.",
    file = "src/advanced.py",
    cursor = { 4, 22 },
  },
  {
    category = "LSP",
    instruction = "Place cursor on 'Calculator' and press gD to see all usages across files.",
    hint = "gD opens a Telescope picker with all references. Enter jumps to the selected one.",
    file = "src/calculator.py",
    cursor = { 1, 6 },
  },
  {
    category = "LSP",
    instruction = "Hover over 'add' method and press K to see its documentation.",
    hint = "K shows the function signature and docstring in a floating popup.",
    file = "src/calculator.py",
    cursor = { 5, 8 },
  },
  {
    category = "Treesitter",
    instruction = "Place cursor inside the 'add' method body and press vaf to select the entire function.",
    hint = "af = 'around function'. Try vif for just the body. Also works: vac (around class).",
    file = "src/calculator.py",
    cursor = { 7, 8 },
  },
  {
    category = "Treesitter",
    instruction = "Use ]f to jump to the next function. Then [f to go back.",
    hint = "]f and [f jump between function boundaries. ]c and [c jump between classes.",
    file = "src/calculator.py",
    cursor = { 1, 0 },
  },
  {
    category = "Editing",
    instruction = "Select lines 7-8 in visual mode (V) and press J to move them down.",
    hint = "In visual mode, J moves selection down, K moves it up.",
    file = "src/calculator.py",
    cursor = { 7, 0 },
  },
  {
    category = "Clipboard",
    instruction = "Yank a line with <leader>y then paste it outside Neovim with Cmd+V.",
    hint = "<leader>y copies to the system clipboard. <leader>Y yanks the entire line.",
    file = "src/calculator.py",
    cursor = { 5, 0 },
  },
  {
    category = "Buffers",
    instruction = "Open both files, then use <S-l> and <S-h> to cycle between buffer tabs.",
    hint = "Shift+L = next buffer, Shift+H = previous. <leader>bp picks by letter overlay.",
    file = "src/calculator.py",
  },
  {
    category = "Harpoon",
    instruction = "Pin this file with <leader>pa. Open advanced.py and pin it too. Then use <leader>1 and <leader>2 to switch.",
    hint = "<leader>pp shows the harpoon menu. <leader>1-4 jump directly to pinned files.",
    file = "src/calculator.py",
  },
  {
    category = "File Tree",
    instruction = "Press <leader>e to toggle the file tree. Navigate to advanced.py and press Enter.",
    hint = "<leader>E reveals the current file in the tree. <leader>h/l to move between tree and editor.",
    file = "src/calculator.py",
  },
  {
    category = "Oil",
    instruction = "Press - to open the parent directory as an editable buffer.",
    hint = "In oil, rename files by editing text. :w to apply changes. Enter to open a file.",
    file = "src/calculator.py",
  },
  {
    category = "TODO Comments",
    instruction = "Press <leader>ft to find all TODO/FIXME comments across the project.",
    hint = "The TODO and FIXME on lines 21-22 should appear in the Telescope results.",
    file = "src/calculator.py",
    cursor = { 21, 0 },
  },
  {
    category = "Git",
    instruction = "Press gb to toggle inline blame on all lines.",
    hint = "Each line shows author and date. Colors indicate age: brighter = newer, dimmer = older.",
    file = "src/calculator.py",
  },
  {
    category = "Surround",
    instruction = "Place cursor on 'result' (line 7) and press ysiw\" to surround it with double quotes.",
    hint = "ysiw\" = 'you surround inner word with quotes'. cs\"' changes quotes. ds\" deletes them.",
    file = "src/calculator.py",
    cursor = { 7, 8 },
  },
  {
    category = "Commenting",
    instruction = "Press gcc to toggle a comment on the current line. Select 3 lines with V and press gc.",
    hint = "gcc toggles a single line. gc in visual mode toggles the selection.",
    file = "src/calculator.py",
    cursor = { 7, 0 },
  },
  {
    category = "Cheatsheet",
    instruction = "Press ? to open the keybinding cheatsheet. Search for 'blame' to find the git blame binding.",
    hint = "Enter previews the Lua source. <C-d> opens the category docs. Esc returns to the list.",
    file = "src/calculator.py",
  },
  {
    category = "Windows",
    instruction = "Split the window with :vsp. Use <leader>h and <leader>l to move between windows.",
    hint = "<leader>h/j/k/l moves focus. <C-arrows> resizes windows.",
    file = "src/calculator.py",
  },
  {
    category = "Undo Tree",
    instruction = "Make a few edits, then press <leader>u to open the visual undo tree.",
    hint = "Navigate undo branches visually. Press q to close.",
    file = "src/calculator.py",
  },
}
